stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/iris.csv
    outs:
      - models/model.pkl
    metrics:
      - metrics/results.json:
          cache: false
    plots:
      - metrics/results.json