stages:
  prepare_data:
    cmd: /opt/anaconda3/bin/python src/train.py prepare_data
    deps:
      - src/train.py
    outs:
      - data/iris.csv
  
  train_model:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/iris.csv
    outs:
      - models/iris_model.joblib
      - metrics/metrics.json
      - plots/confusion_matrix.png
  
  experiment1:
    cmd: /opt/anaconda3/bin/python src/experiment.py run_experiment --max_iter 100
    deps:
      - src/experiment.py
      - data/iris.csv
    outs:
      - metrics/metrics_100.json
      - plots/confusion_matrix_100.png
  
  experiment2:
    cmd: /opt/anaconda3/bin/python src/experiment.py run_experiment --max_iter 300
    deps:
      - src/experiment.py
      - data/iris.csv
    outs:
      - metrics/metrics_300.json
      - plots/confusion_matrix_300.png
